app:
    files:
        path: /home/scylla/esutoniagodesu/egd-files/

mail:
    host: smtp.gmail.com
    port: 587
    username: esutoniagodesu@gmail.com
    password: Natsuyasumi1
    protocol: smtp
    tls: true
    auth: true
    from: esutoniagodesu@gmail.com

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/egd
        username: egdrole
        password: changeit

    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: 895236925067-lvj3sbgoqq6a6t7od3s130lrudqmfaqh.apps.googleusercontent.com
            clientSecret: 8qbJ2uNeaJf8jzaFos4FD_UL

        facebook:
            clientId: 1597103220538979
            clientSecret: 56a0d7878eb9bd54ca5e609b0c4cfc98

google:
    translate-service:
        clientId: esutoniagodesu-dev
        clientSecret: AIzaSyCmMlaAiIk5oDNa7f0wsTNH3MfkRP3RR7M

microsoft:
    translate-service:
        clientId: esutoniagodesu
        clientSecret: qkAx7U5QVpvDh7kVijUhCkofH7Dd9My4RzlkXPwlM2g=
