# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.hbm2ddl.auto: validate
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    jmx:
        enabled: false
    thymeleaf:
        mode: XHTML

server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

security:
    basic:
        enabled: false

app:
    async:
        corePoolSize: 2
        maxPoolSize: 10
        queueCapacity: 10000
