spring:
    jmx:
        enabled: false

    profiles:
        active: prod

    mail:
        baseUrl: https://localhost:8443

    thymeleaf:
        mode: XHTML
        cache: true

http:
    cache:
        timeToLiveInDays: 31

app.security.activation-required: false
