# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable default favicon
spring.mvc.favicon.enabled: false

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
