app:
    url: https://momo.koodur.com

spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    mail:
        baseUrl: https://momo.koodur.com
    thymeleaf:
        cache: true

http:
    cache:
        timeToLiveInDays: 31
