server:
    port: 8443
    ssl:
        key-store: ssl/localhost.keystore
        key-store-password: changeit
        key-alias: tomcat
        trust-store: ssl/egd.truststore
        trust-store-password: changeit
        client-auth: want

spring:
    profiles:
        active: dev

    mail:
        baseUrl: https://localhost:8443

    messages:
            cache-seconds: 1

    thymeleaf:
        mode: XHTML
        cache: false

app.security.activationRequired: false
