app:
    url: https://momo.koodur.com

spring:
    profiles:
        active: prod
    mail:
        baseUrl: https://momo.koodur.com
    thymeleaf:
        cache: true

http:
    cache:
        timeToLiveInDays: 31
