spring:
    profiles:
        active: prod

    datasource:
        jndi: java:comp/env/jdbc/egd

    mail:
        baseUrl: https://localhost:8443

    thymeleaf:
        mode: XHTML
        cache: true

http:
    cache:
        timeToLiveInDays: 31

microsoft:
    translate-service:
        id: esutoniagodesu
        secret: qkAx7U5QVpvDh7kVijUhCkofH7Dd9My4RzlkXPwlM2g
