server:
    port: 8080

spring:
    profiles:
        active: prod
    datasource:
        jndi-name: java:comp/env/jdbc/egd

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false


    data:
        elasticsearch:
            cluster-name:
            cluster-nodes: localhost:9200
    thymeleaf:
        mode: XHTML
        cache: true
http:
    cache:
        timeToLiveInDays: 31


