app:
    files:
        path: /usr/local/tomcat/egd-files/
    multimedia:
        datasource:
            driver-class-name: org.h2.jdbcx.JdbcDataSource
            url: jdbc:h2:file:/usr/local/tomcat/egd-files/shadb.db;DB_CLOSE_DELAY=-1
            username:
            password:
    mail:
        host: smtp.gmail.com
        port: 587
        username: esutoniagodesu@gmail.com
        password: Natsuyasumi1
        protocol: smtp
        tls: true
        auth: true
        from: esutoniagodesu@gmail.com
    translate-service:
        google:
            clientId: esutoniagodesu-prod
            clientSecret: AIzaSyDGtTp0nOEfyr_iIVcsnOO_k7ILFK3Vm_4
        microsoft:
            clientId: esutoniagodesu
            clientSecret: qkAx7U5QVpvDh7kVijUhCkofH7Dd9My4RzlkXPwlM2g=

spring:
    datasource:
        jndi: java:comp/env/jdbc/egd

    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: 405199176236-0k62prog43de96l73up50lcrurn4kkc2.apps.googleusercontent.com
            clientSecret: NGRFXbacSen7TXqHoDUzgkYh

        facebook:
            clientId: 1617135431886378
            clientSecret: 455772b3189449a5e8c04fa5203330f7
