app:
    url: https://localhost:8443

server:
    port: 8443
    ssl:
        key-store: ssl/localhost.jks
        key-store-password: changeit
        key-alias: tomcat
        trust-store: ssl/egd.truststore
        trust-store-password: changeit
        client-auth: want

spring:
    jpa:
        show_sql: false
        properties:
            hibernate.generate_statistics: true
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    mail:
        baseUrl: https://localhost:8443
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
