app:
    url: https://momo.koodur.com
    http:
        cache:
            timeToLiveInDays: 31

spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    mail:
        baseUrl: https://momo.koodur.com
    thymeleaf:
        cache: true


