app:
    url: https://momo.koodur.com

server:
    port: 8080

spring:
    jmx:
        enabled: false

    profiles:
        active: prod

    mail:
        baseUrl: https://momo.koodur.com

    thymeleaf:
        mode: XHTML
        cache: true

http:
    cache:
        timeToLiveInDays: 31
