app:
    url: https://momo.koodur.com

spring:
    profiles:
        active: prod

    mail:
        baseUrl: https://momo.koodur.com

    thymeleaf:
        mode: XHTML
        cache: true

http:
    cache:
        timeToLiveInDays: 31
