spring:
    profiles:
        active: prod

    datasource:
        jndi-name: java:comp/env/jdbc/egd

    mail:
        baseUrl: https://localhost:8443

    thymeleaf:
        mode: XHTML
        cache: false
