server:
    port: 8080

spring:
    profiles:
        active: dev

    datasource:
        #jndi: java:comp/env/jdbc/egd
        url: jdbc:postgresql://localhost:5432/egd
        username: postgres
        password: redherring

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error
